name: rpgpickr
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.15.3
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/picklogo.png"

flutter_native_splash:
  background_image: "assets/icons/splash.png"


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
