// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmbRqpf2ujXNoaFQs50lTSGS2mH06g4oI',
    appId: '1:686515888254:web:e0594b365fea242013f82f',
    messagingSenderId: '686515888254',
    projectId: 'rpg-picking-dingsydangsy',
    authDomain: 'rpg-picking-dingsydangsy.firebaseapp.com',
    storageBucket: 'rpg-picking-dingsydangsy.appspot.com',
    measurementId: 'G-206ELNKDJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuVOjjTzOToXc4o4SHAkaudz9zmf6B0w',
    appId: '1:686515888254:android:43b6e07fde99ab9c13f82f',
    messagingSenderId: '686515888254',
    projectId: 'rpg-picking-dingsydangsy',
    storageBucket: 'rpg-picking-dingsydangsy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjwqOoesBzdvmc_WftpcQoipAT-Igej1o',
    appId: '1:686515888254:ios:05d0638269333e2913f82f',
    messagingSenderId: '686515888254',
    projectId: 'rpg-picking-dingsydangsy',
    storageBucket: 'rpg-picking-dingsydangsy.appspot.com',
    iosBundleId: 'com.example.rpgpickr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjwqOoesBzdvmc_WftpcQoipAT-Igej1o',
    appId: '1:686515888254:ios:05d0638269333e2913f82f',
    messagingSenderId: '686515888254',
    projectId: 'rpg-picking-dingsydangsy',
    storageBucket: 'rpg-picking-dingsydangsy.appspot.com',
    iosBundleId: 'com.example.rpgpickr',
  );
}
